# Generated by Django 5.0.7 on 2024-07-26 06:03

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0005_alter_thumbnails_options_alter_videos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
