# Generated by Django 5.0.7 on 2024-07-20 10:56

import django.core.validators
import django.utils.timezone
import media_files.fields
import media_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/thumbnails/', validators=[media_files.models.validate_image_file])),
                ('language', media_files.fields.ThumbnailLanguageField(blank=True, null=True)),
                ('game', media_files.fields.GameField()),
                ('date_uploaded', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('video_url', models.URLField(null=True, validators=[django.core.validators.URLValidator()])),
                ('language', media_files.fields.VideoLanguageField(null=True)),
                ('game', media_files.fields.GameField()),
                ('client', media_files.fields.ClientField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('date_uploaded', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
