# Generated by Django 5.0.7 on 2024-07-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0003_alter_thumbnail_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thumbnail',
            new_name='Thumbnails',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='Videos',
        ),
    ]
