# Generated by Django 5.0.7 on 2024-07-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0004_rename_thumbnail_thumbnails_rename_video_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thumbnails',
            options={'verbose_name': 'Thumbnail', 'verbose_name_plural': 'Thumbnails'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
