# Generated by Django 5.0.7 on 2024-07-26 07:13

import media_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0006_videos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='thumbnails',
            name='image',
            field=models.ImageField(null=True, upload_to='thumbnails/', validators=[media_files.models.validate_image_file]),
        ),
    ]
