# Generated by Django 5.0.7 on 2024-07-26 08:14

import media_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0007_remove_videos_video_url_alter_thumbnails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnails',
            name='image',
            field=models.ImageField(null=True, upload_to='media/thumbnails/', validators=[media_files.models.validate_image_file]),
        ),
    ]
